<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Microsoft.CodeAnalysis.Workspaces.UnitTests</AssemblyName>
    <RootNamespace>Codewise.RoslynInternalAccess</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <RestoreAdditionalProjectSources>$(RestoreAdditionalProjectSources);https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json</RestoreAdditionalProjectSources>
    <KeyOriginatorFile>$(PkgMicrosoft_DotNet_Arcade_Sdk)\tools\snk\35MSSharedLib1024.snk</KeyOriginatorFile>
    <PublicSign>true</PublicSign>
  </PropertyGroup>

  <ItemGroup>
    <PackageDownload
      Include="roslyn-language-server.win-x64"
      Version="[5.12.0-1.26426.8]" />
    <PackageReference
      Include="Microsoft.DotNet.Arcade.Sdk"
      Version="9.0.0-beta.24372.7"
      PrivateAssets="all"
      IncludeAssets="none"
      GeneratePathProperty="true" />
    <Reference
      Include="Microsoft.CodeAnalysis"
      HintPath="$(NuGetPackageRoot)roslyn-language-server.win-x64/5.12.0-1.26426.8/tools/net10.0/win-x64/Microsoft.CodeAnalysis.dll"
      Private="false" />
    <Reference
      Include="Microsoft.CodeAnalysis.Workspaces"
      HintPath="$(NuGetPackageRoot)roslyn-language-server.win-x64/5.12.0-1.26426.8/tools/net10.0/win-x64/Microsoft.CodeAnalysis.Workspaces.dll"
      Private="false" />
  </ItemGroup>

</Project>
